### ISSUE TITLE
Please update API version in example to v1

### ISSUE THREAD

**Issue by gtomilko** [NetAppDocs/trident#276]
Page: [Kubernetes and Trident objects](https://docs.netapp.com/us-en/trident/trident-reference/objects.html#kubernetes-volumesnapshotclass-objects)

I was breaking my head why my Rancher complains "no reference".  
``` yaml
apiVersion: snapshot.storage.k8s.io/v1beta1 # It should be v1 here
kind: VolumeSnapshotClass
metadata:
  name: csi-snapclass
driver: csi.trident.netapp.io
deletionPolicy: Delete
```
