### ISSUE TITLE
SnapShot import procedure

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#348]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html

### Page title

Work with snapshots

### Summary

Hi,

the snapshot import procedure is not clear.

Step1 gives as example the following:
```
...
kind: VolumeSnapshotContent
metadata:
  name: my-trident-snapshot-content
...
  volumeSnapshotRef:
    name: test-snapshot
    namespace: default
...
```

Step2 specifies :
Bind the VolumeSnapshot to the VolumeSnapshotContent where **volumeSnapshotContentName is the name you specified in volumeSnapshotRef.**
The corresponding example shows:
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-snapshot
  namespace: default
spec:
  source:
    volumeSnapshotContentName: my-trident-snapshot-content
```

The example from step2 does not correspond to step1 if you follow the guidelines.
if volumeSnapshotContentName = volumeSnapshotRef, the field should then be _test-snapshot_

so what is the correct procedure?

thanks for your help on this...

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.
