### ISSUE TITLE
"Create an application CR" shows invalid YAML

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/trident#527]
### Page URL

https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-manage-applications.html

### Page title

Define an application for management

### Summary

The example YAML manifest in the section `Create an application CR` shows invalid YAML code. The includedNamespaces section requires an array. The provided example won't work. Also see https://github.com/NetApp/trident/issues/955

Can you please correct the YAML code. The following is a working example:

```
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: maria
  namespace: my-app-namespace
spec:
  includedNamespaces:
    - namespace: my-app-namespace

```

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.
